services:
  backend-twomarkdown:
    container_name: twomarkdown_backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - .env
    environment:
      - UV_PROJECT_ENVIRONMENT=/opt/venv
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet_twomarkdown

networks:
  appnet_twomarkdown:
